# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8b57547a627f517680ed3858922735f3b8af3b92a4aeaf0d2ac3953595543cab8caeaf2356c169386146466fb798a1cc2757c06ef3ab60b22b847373370b42d

test:
  secret_key_base: af0d514e29fb0c15b705ea8453ea6e912c5121134ae883b0eb9a1d354b8591b6e186a7485951b13f33a74d19bedde5a6ca96d508690dfeebd25353b1cbb7532b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
