# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coordinator_email', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('end_date', models.DateTimeField(verbose_name='date ended')),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_email', models.CharField(max_length=255)),
                ('landlord_phone_num', models.CharField(max_length=255)),
                ('rent', models.CharField(max_length=255)),
                ('address_id', models.IntegerField(default=0)),
                ('residence_reviews', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('class_standing', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number', models.IntegerField(default=0)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
    ]
