# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='address_id',
        ),
    ]
